name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run a simple Node.js script to print Hello World Node-Js Project!
      run: |
        node app.js

    - name: Build Docker image
      run: |
        docker build -t hello-world-nodejs .

    - name: Scan Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: hello-world-nodejs

    - name: Run Docker container
      run: |
        docker run hello-world-nodejs

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hello-world-artifact
        path: |
          .
          !node_modules/