name: CI

# Trigger the workflow on push events
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Node.js environment with version 20
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Install project dependencies
    - name: Install dependencies
      run: npm install

    # Run a simple Node.js script to print a message
    - name: Run a simple Node.js script to print Hello World Node-Js Project!
      run: |
        node app.js

    # Build Docker image from the Dockerfile
    - name: Build Docker image
      run: |
        docker build -t hello-world-nodejs .

    # Scan the Docker image for vulnerabilities using Trivy
    - name: Scan Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: hello-world-nodejs

    # Run the Docker container to print "Hello World" to the console
    - name: Run Docker container
      run: |
        docker run hello-world-nodejs

    # Upload compiled artifacts to GitHub artifact repository
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hello-world-artifact
        path: |
          .
          !node_modules/
